#!/bin/bash

npm init
mkdir -p src/bin
echo "#!/usr/bin/env node" >> src/bin/gendiff.js
chmod +x src/bin/gendiff.js
sudo npm install --save-dev @babel/core @babel/cli @babel/node @babel/preset-env eslint eslint-config-airbnb-base eslint-plugin-import babel-eslint
echo "module.exports = {
  presets: [
    ['@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
};" >> babel.config.js

echo "language: node_js

node_js: 
  - node

script:
- make lint" >> .travis.yml

echo "env:
  node: true

plugins:
  - import

parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0" >> .eslintrc.yml

echo "dist" >> .eslintignore

echo "install: 
	sudo npm install

start:
	sudo npx babel-node src/bin/brain-games.js

publish:
	npm publish

lint:
	npx eslint ." >> Makefile

git init
echo "node_modules
dist" >> .gitignore
